---
name: Deploy Workflow

on:
  push:
    branches:
      - main
    tags:
      - "v**"
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stg
          - prod

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: ${{ (github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')) && 'production' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # env: dev
      - name: Deploy to dev
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.env == 'dev') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main') }}
        run: echo "dev"
      # env: stg
      - name: Deploy to stg
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.env == 'stg') || (github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.ref_name, 'release-v')) }}
        run: echo "stg"
      # env: prod
      - name: Deploy to prod
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.env == 'prod') || (github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')) }}
        run: echo "prod"